-   repo: https://github.com/chriskuehl/puppet-pre-commit-hooks.git
    sha: 4bc20784cca4713e2ba5f884ff4c37a1e4e87de1
    hooks:
    -   id: puppet-validate
    -   id: erb-validate
    -   id: puppet-lint
        args:
        -   --fail-on-warnings
        -   --relative
        -   --no-80chars-check
        -   --no-documentation-check
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: 003e43251aea1da33f2072f2365ec8b9ceaae070
    hooks:
    -   id: check-added-large-files
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
