---
.travis.yml:
  secure: "QgLSIFsMCb7nDLbkrxI8mfgs55Had+PgwVZ/uwrYmHKC/5QKLNQKDtjIBxd0OMTdbh0ZorkpaDF9SRwSkCNEOZcuATuCvrhn8HT8xo6NQbXUIcRWeq/A4T94z3okEg6gNTgyTkeQ5vlN+OscIrkHGVDY37qMU03CEx158SQ9Cf7Hd7+DqWNphh2Ne6xuweA20eBdOPvH0RISxO6rVjEHKGxE/h0BWhVrTjGN8DhCYlIvzPByE0vnUo2W+j5PIy9xs1ePO5hiyyhmMeCDgdcAI3DODYULL/8cL3PXlXFfmXhiWQIGlFv1DxAiaCRzMrynF9UH4TDJHuT9FG/qAl3LrM21E/GwVxp5ntcounOOWjcCDwOCOTrWq+N2kGOX3SjdOQ9UcuLhrY75U+F+/PBQz1FSGkQX6+yzgK5f5Ki0XAOprArXRryTcCgPKlZVr5F+tZMJON3u3eEiIKs7AxEpfLT1n2XHVgpQsek/Otf6iHrVgHuZZVRLGz/FbN2oAUXfZBknnwbvbErswDmiv99Lx7guX5kJpBR2IDYyk1GKACJVFA3BQXyVL0d/vjjSmCkTzLGkKplNaTr8PzwNiptVmm3w8og9wNji3jPxEbUAEVlhercKm5eHbTLJR5bpByVFKr0muvKmA3IUQfWW7KVDE4XNfH9bog7jba3qfAsz0sQ="
  unmanaged: true
spec/acceptance/nodesets/ec2/amazonlinux-2016091.yml:
  delete: true
spec/acceptance/nodesets/ec2/image_templates.yaml:
  delete: true
spec/acceptance/nodesets/ec2/rhel-73-x64.yml:
  delete: true
spec/acceptance/nodesets/ec2/sles-12sp2-x64.yml:
  delete: true
spec/acceptance/nodesets/ec2/ubuntu-1604-x64.yml:
  delete: true
spec/acceptance/nodesets/ec2/windows-2016-base-x64.yml:
  delete: true
spec/acceptance/nodesets/archlinux-2-x64.yml:
  delete: true
